controller_joint_names: ['', 'Joint-11', 'Joint-12', 'Joint-13', 'Joint-14', 'Joint-21', 'Joint-22', 'Joint-23', 'Joint-24', 'Joint-31', 'Joint-32', 'Joint-33', 'Joint-34', 'Joint-41', 'Joint-42', 'Joint-43', 'Joint-44', ]
